/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'adhithya' at '21/5/18 2:25 PM' with Gradle 2.14.1
 *
 * @author adhithya, @date 21/5/18 2:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
