import java.io.IOException;
import java.security.GeneralSecurityException;

import org.apache.commons.ssl.OpenSSL;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String args[]) throws IOException, GeneralSecurityException{
    	
    	String data="Test123";
        String key="AABBCC11";
        String cipher=new String(OpenSSL.encrypt("AES256", key.toCharArray(), data.getBytes(), true));
        //cipher=enc(data,key);
        String clear=new String(OpenSSL.decrypt("AES256", key.toCharArray(), cipher.getBytes()));
        System.out.println(clear);
    	
    }
}
