/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user' at '15/10/16 2:48 PM' with Gradle 2.9
 *
 * @author user, @date 15/10/16 2:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
